
# curl -X POST http://localhost:4000/auth -d '{"username": "eswang", "password": "3333"}' -H "Content-Type: application/json"
curl http://localhost:4000/admin/posts
# curl http://localhost:4000/admin/posts -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1Nzk0MjM5MDMsImV4cCI6MTU3OTQ4MzkwM30.x_h9YNLuZbY6-vQ2b2ysPrmD1JhqRkbhrKCUyYinWtg